name: CD

on:
  push:
    tags:
      - v1.**
      
permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    
    - name: Build
      run: python -m pip install -r requirements.txt && python -m PyInstaller --onefile --windowed gui.py --hidden-import=can.interfaces.slcan --hidden-import=can.interfaces.serial --hidden-import=serial
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        working_directory: dist
        files: gui.exe

  build-macos:
    needs: build-windows
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Build
      run: python -m pip install -r requirements.txt && python -m PyInstaller --onefile --windowed gui.py --hidden-import=can.interfaces.slcan --hidden-import=can.interfaces.serial --hidden-import=serial
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        working_directory: dist
        files: gui.app

  build-linux:
    needs: build-macos
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    
    - name: Build
      run: python -m pip install -r requirements.txt && python -m PyInstaller --onefile --windowed gui.py --hidden-import=can.interfaces.slcan --hidden-import=can.interfaces.serial --hidden-import=serial
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        working_directory: dist
        files: gui
