name: CD

on:
  push:
    tags:
      - v1.**
      
permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    
    - name: Build
      run: python -m pip install -r requirements.txt && python -m PyInstaller --name CANViewer --onefile --windowed gui.py --hidden-import=can.interfaces.slcan --hidden-import=can.interfaces.serial --hidden-import=serial
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        working_directory: dist
        files: CANViewer.exe

  build-macos:
    needs: build-windows
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Build
      run: python -m pip install -r requirements.txt && python -m PyInstaller --name CANViewer --windowed gui.py --hidden-import=can.interfaces.slcan --hidden-import=can.interfaces.serial --hidden-import=serial
    
    - name: Zip Up App
      run: zip -r dist/CANViewer.zip dist/CANViewer.app
      
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        working_directory: dist
        files: CANViewer.zip

  build-linux:
    needs: build-macos
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Tkinter
      run: sudo apt install python3-tk
      
    - name: Checkout
      uses: actions/checkout@v6
    
    - name: Build
      run: python -m pip install -r requirements.txt && python -m PyInstaller --name CANViewer --onefile gui.py --hidden-import=can.interfaces.slcan --hidden-import=can.interfaces.serial --hidden-import=serial
    
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        working_directory: dist
        files: CANViewer
